src/main/java/conflux/web3j/Cfx.java, src/main/java/conflux/web3j/Web3j.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/4)
=> add generic request method

.gitignore, src/main/java/conflux/web3j/Account.java
FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/6)
=> Update account transfer method to support gasLimit in option

src/main/java/conflux/web3j/Cfx.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/10)
=> add extra parameter(retry,interval) to service build method

build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/11)
=> bump web3j version to 4.6.3

README.md, src/main/java/conflux/web3j/response/Receipt.java
easily get tx exec fail message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/13)
=> receipt add field: txExecErrMsg

src/main/java/conflux/web3j/Cfx.java, src/main/java/conflux/web3j/Web3j.java, src/main/java/conflux/web3j/response/DepositInfo.java, src/main/java/conflux/web3j/response/Receipt.java, src/main/java/conflux/web3j/response/StorageChange.java, src/main/java/conflux/web3j/response/SupplyInfo.java, src/main/java/conflux/web3j/response/TokenSupplyInfo.java, src/main/java/conflux/web3j/response/VoteStakeInfo.java
getVoteList, getDepositList
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/14)
=> add support for new rpc

src/main/java/conflux/web3j/AccountManager.java, src/main/java/conflux/web3j/contract/ContractCall.java, src/main/java/conflux/web3j/contract/ERC20.java, src/main/java/conflux/web3j/contract/internals/AdminControl.java, src/main/java/conflux/web3j/contract/internals/SponsorWhitelistControl.java, src/main/java/conflux/web3j/contract/internals/Staking.java
1. Set call data to null when encoding empty method.
2. Add API in `AccountManager` to export account private key.
3. Remove unused imports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/16)
=> fix issues for call data

README.md, build.gradle, docs/cfx-address.md, src/main/java/conflux/web3j/Web3j.java, src/main/java/conflux/web3j/request/LogFilter.java, src/main/java/conflux/web3j/types/Address.java, src/main/java/conflux/web3j/types/AddressType.java, src/test/java/conflux/web3j/types/RPCTests.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/19)
=> fix gradle build failed

src/main/java/conflux/web3j/contract/ERC20.java, src/main/java/conflux/web3j/contract/internals/AdminControl.java, src/main/java/conflux/web3j/contract/internals/SponsorWhitelistControl.java, src/main/java/conflux/web3j/types/Address.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/21)
=> fix bugs of cfx address

README.md, build.gradle, src/main/java/conflux/web3j/contract/ERC20.java, src/main/java/conflux/web3j/contract/ERC777.java, src/main/java/conflux/web3j/contract/internals/AdminControl.java, src/main/java/conflux/web3j/contract/internals/SponsorWhitelistControl.java, src/main/java/conflux/web3j/contract/internals/Staking.java, src/main/java/conflux/web3j/types/Address.java, src/main/java/conflux/web3j/types/CfxAddress.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/22)
=> When interact with contract method use AbiAddress

CHANGELOG.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/23)
=> update readme web3j.core version

src/main/java/conflux/web3j/Account.java, src/main/java/conflux/web3j/crypto/ConfluxBase32Exception.java, src/main/java/conflux/web3j/request/LogFilter.java, src/main/java/conflux/web3j/response/Status.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/26)
=> add more api for Account class

docs/contract-interaction.md, src/main/java/conflux/web3j/Account.java, src/main/java/conflux/web3j/contract/internals/CrossSpaceCall.java, src/main/java/conflux/web3j/contract/internals/PoSRegister.java, src/main/java/conflux/web3j/types/Address.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/34)
=> feat: adapt to PoSRegister and CrossSpace internal contracts

README.md, build.gradle, docs/getting-started.md, docs/how-to-publish.md, src/main/java/conflux/web3j/Account.java, src/main/java/conflux/web3j/types/RawTransaction.java, src/main/java/conflux/web3j/types/TransactionBuilder.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/35)
=> Update default timeout

src/main/java/conflux/web3j/response/events/NewHead.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/40)
=> fix the null problem

src/main/java/conflux/web3j/Account.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/41)
=> add the random account and getprivateKey

CHANGELOG.md, README.md, build.gradle, docs/batch-rpc.md, src/main/java/conflux/web3j/Account.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/42)
=> add batch rpc

src/main/java/conflux/web3j/response/Receipt.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/java-conflux-sdk/44)
=> add the gasFee

src/main/java/conflux/web3j/AccountManager.java, src/main/java/conflux/web3j/types/Address.java, src/main/java/conflux/web3j/types/AddressType.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/java-conflux-sdk/47)
=> Add address type

build.gradle, src/main/java/conflux/web3j/AMNAccount.java, src/main/java/conflux/web3j/Account.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/java-conflux-sdk/49)
=> add a self manage account method

CHANGELOG.md, build.gradle, src/main/java/conflux/web3j/types/SendTransactionError.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/java-conflux-sdk/48)
=> SendTransactionError parse bug deal data is null
